### ISSUE TITLE
Change font icons to use SVG icon sprites

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#17]
- Remove support for font icons and use SVG icons sprites instead.

- Update fonts dir and styles

**Comment by adamf321** [comment]
A gulp task for combining the SVG's is already in the start kit...

**Comment by mitogh** [comment]
Cool yes I think we can reuse some of that to make it more easy to add new icons into the icon set, I think the process to drop an SVG into a folder is more easier to mantain as well than regular icon fonts to add / remove a new icon.
