### ISSUE TITLE
Consolidate NPM scripts and Gulp

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#21]
Any of those should be used for build in a consistent way so all commands are NPM Scripts or all commands are `gulp commands`

**Comment by adamf321** [comment]
Agreed. My vote is for gulp as it's easier to write more complex scripts.

**Comment by mitogh** [comment]
Sounds good `gulp` is going to be then.

**Comment by mitogh** [comment]
Closing this one since the `NPM scripts` has been removed and is using only `gulp`
