### ISSUE TITLE
Update automatic loading of files under Modules

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#29]
At the moment the automatic process to include a file requires to have a file with the same name of the directory example: 

```php
Widgets/Widgets.php
```

Which eventually ends up in a namespace such as

```php
// Widgets.php file
namespace LeanNs\Modules\Widgets;

class Widgets {
} 
```

And a usage or call of a file (if required) of something like: 

```php
use Modules\Widgets\Widgets;
```

**Comment by adamf321** [comment]
I think this is ok. What's your suggestion @mitogh ?

**Comment by mitogh** [comment]
Sorry I forgot to add that. I was thinking to have a convention same as we have for:

-  `scss` all entry files are called `_style` 
- `js` all entry files are called `index.js`

**Comment by adamf321** [comment]
The issue with that is how you use the class... If it they're all called Index.php for example then you might have several uses:
 
```
use Modules\Widgets\Index;
use Modules\SomethingElse\Index;
...
```

And so you have to do `use ... as ... ;` all the time to make the names unique.

To me `\Modules\Widgets\Widgets' is ok ... and it's quite commonly used in other packages.

**Comment by mitogh** [comment]
Yes I'm open to use any style however I think making the assumption to load that one as the one that bootstrap automatically is what's I think we should define a convention around what classes should bootstrap automatically or just define a way to set those more explicitly.

**Comment by adamf321** [comment]
Convention seems best to me, or at least for it to be defined within the module itself. Do you have a proposal?

**Comment by adamf321** [comment]
I think defining it in the module is best. Otherwise we get the same problem is we use `Bootstrap`or something for all modules.
Or we could have a convention that the `Bootstrap` class never has any code which can be called externally, it only fires internal init functions within the module itself.

**Comment by mitogh** [comment]
Yes something like that would work I think at least we have some convention we can follow is great. Maybe a default base `Bootstrap` might help.
