### ISSUE TITLE
Base namespace LeanNs

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#4]
- What are the meaning of `Ns` I think if we have just `Lean` should be enough, no?

**Comment by adamf321** [comment]
The idea is that this allows us to make the generator a bit cleverer. So we can automaitcally replace all instances of `LeanNs` with the chosen namespace. All instances of `LeanName` with the chosen name, etc.

**Comment by mitogh** [comment]
Sounds good. We need to make a not on the `readme.md` I guess.

**Comment by adamf321** [comment]
I already did... it's here: https://github.com/moxie-lean/lean-theme/blob/master/docs/getting-started.md#update-information
