### ISSUE TITLE
Discussion about build tools placement

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#45]
I think it makes sense to have the theme `agnostic` of the build tools of the patterns, what I mean by that is the theme should only have a `lint` for the `.php` files since is the only thing that the theme always should care and remove any other: 

- `package.json`
- `gulpfile`
- `bower`

Since those things should be part of the `patterns` instead of the theme so for example at some point anyone should be able to plug any `patterns` directory with any type of structure for build tools like: 

- NPM Scripts
- gulpfile
- Webpack or whatever.

Since those tools are only used during the generation of the final `static` assets. So we can just those kind of elements into the `patterns` directory instead of the `theme`. 

Please share your comments about this.

**Comment by adamf321** [comment]
Sounds ok. I think we should just include wrapper tasks for the build-deps and build-apps tasks in composer.json.

**Comment by mitogh** [comment]
Closing this one since final solution is described on https://github.com/moxie-lean/lean-theme/issues/51
