### ISSUE TITLE
Consisten rule on class structure.

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#5]
We should follow the same patter to write a new function or class at the moment we have: 

``` php
// For classes
class Patterns
{
 /// Code
}
```

``` php
// For methods
public static function init() {
  // Code
}
```

Either way is fine with me as long as is consistent across all the site.

**Comment by adamf321** [comment]
Is there a php lint rule for this? My personal preference is for the first option, but it's not a big deal either way.

**Comment by mitogh** [comment]
There is one but is not yet on the WP Sniffer Repo.
