### ISSUE TITLE
Add alias in composer.json for the build task

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#51]
Add alias to the tasks that creates the  bundle and build the JS and CSS, icons, images and so on.

**Comment by adamf321** [comment]
This PR shows how the project scripts should look: https://bitbucket.org/WeAreNolte/nystec.com/pull-requests/16/deploy-scripts/diff

The basic idea is that the Deploybot scripts are always the same for all php projects (i.e. WordPress). For JS projects we can use the same, just replacing “composer” with “npm run”.

Each composer file in the project (in the case of nystec there are 2: the root and the nystec theme) contains 3 scripts:
- build-deps: installs all dependencies at this level and child levels. Eg:
   - composer build-deps in the root runs composer install for the root and then composer build-deps for the theme.
   - composer build-deps in the theme runs composer install for itself and then npm install and bower install.
- build-app: builds the app (e.g. compiles SASS). Same logic as above.
- build: is a wrapper which runs build-deps followed by build-app.
