### ISSUE TITLE
Add standard and base animations

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#59]
In order to have a set of standard way to generate basic animations we should make us of a third party library, ideally something that comes as sass mixin in order to prevent increasing of the styles on styling that is not used in many cases.

Examples: 

- http://zurb.com/playground/motion-ui
- https://daneden.github.io/animate.css/

**Comment by Rulox** [comment]
Do we have any preference here @mitogh  ?

**Comment by mitogh** [comment]
No, those are some options if we can search for another set of options so we can have like the best possible option it would be ideal I think. @Rulox
