### ISSUE TITLE
Consider use of the Repo wiki for documentation

### ISSUE THREAD

**Issue by mitogh** [moxie-lean/lean-theme#6]
I think if we use the Wiki for the documentation it makes easier to just update the docs without the need to write any new commits in to the repo.

**Comment by adamf321** [comment]
Can we write to it automatically? The gulp-commands.md file is generated by a gulp task (note the structure of the comments in gulpfile.js for this).

Or we could move the descriptive info to the wiki and keep this generated stuff here in the repo (the same markdox plugin can probable produce php docs as well as js so we can document everything in lean theme this way).

**Comment by adamf321** [comment]
Updated
